BAExamApp.MVC/Areas/CandidateAdmin/Controllers/CandidateQuestionSubjectController.cs
using AutoMapper;
using BAExamApp.Core.Enums;
using BAExamApp.Dtos.Candidate.CandidateQuestionSubject;
using BAExamApp.MVC.Areas.Admin.Models.SubjectVMs;
using BAExamApp.MVC.Extensions;
using Microsoft.EntityFrameworkCore;

namespace BAExamApp.MVC.Areas.CandidateAdmin.Controllers;
public class CandidateQuestionSubjectController : CandidateAdminBaseController
{
    private readonly ICandidateQuestionSubjectService _candidateQuestionSubjectService;
    private readonly IMapper _mapper;
    private readonly ICandidateQuestionService _candidateQuestionService;

    public CandidateQuestionSubjectController(ICandidateQuestionSubjectService candidateQuestionSubjectService, IMapper mapper, ICandidateQuestionService candidateQuestionService)
    {
        _candidateQuestionSubjectService = candidateQuestionSubjectService;
        _mapper = mapper;
        _candidateQuestionService = candidateQuestionService;
    }


    [HttpGet]
    public async Task<IActionResult> Index(bool showAllData = false)
    {
        ViewBag.SubjectList = await _candidateQuestionSubjectService.GetAllAsync();

        var getSubjectListResult = await _candidateQuestionSubjectService.GetAllAsync();
        var subjectList = getSubjectListResult.Data.Adapt<IEnumerable<CandidateAdminQuestionSubjectListVM>>();
        //var subjectList = _mapper.Map<IEnumerable<CandidateAdminQuestionSubjectListVM>>(getSubjectListResult.Data);
        if (!showAllData)
        {
            subjectList = subjectList.Where(subject => subject.Status != Status.Deleted && subject.Status != Status.Passive);
        }
        ViewBag.ShowAllData = showAllData;
        return View(subjectList);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CandidateAdminQuestionSubjectCreateVM viewModel)
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelState.Values.SelectMany(x => x.Errors);
            string errorMessages = null!;

            foreach (var error in errors)
            {
                errorMessages += " ," + error.ErrorMessage;
            }

            NotifyError(errorMessages);

            return RedirectToAction(nameof(Index));
        }

        var subjectCreateVmToDto = viewModel.Adapt<CandidateQuestionSubjectCreateDto>();

        subjectCreateVmToDto.Name = StringExtensions.TitleFormat(viewModel.Name);

        var createSubjectResult = await _candidateQuestionSubjectService.AddAsync(subjectCreateVmToDto);
        if (!createSubjectResult.IsSuccess)
        {
            NotifyErrorLocalized(createSubjectResult.Message);
            return RedirectToAction(nameof(Index));
        }
        NotifySuccessLocalized(createSubjectResult.Message);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Details(Guid id)
    {
        // Konu detaylarını id ile getir
        var subjectDto = await _candidateQuestionSubjectService.GetDetailsByIdAsync(id);

        // Konu içindeki soruların kullanılıp kullanılmadığını kontrol et
        bool isQuestionUsed = await _candidateQuestionSubjectService.IsQuestionUsedInSubjectAsync(id);

        if (subjectDto.IsSuccess)
        {
            // Konu detaylarını ViewModel'e dönüştür
            var subjectDetailDtoToVm = subjectDto.Data.Adapt<CandidateAdminQuestionSubjectDetailVM>();

            subjectDetailDtoToVm.IsQuestionUsed = isQuestionUsed;

            // View'a dön
            return View(subjectDetailDtoToVm);
        }

        // Eğer konu bulunamazsa hata mesajı göster ve Index sayfasına yönlendir
        NotifyErrorLocalized(subjectDto.Message);
        return RedirectToAction(nameof(Index));
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(AdminSubjectUpdateVM viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(nameof(Index));
        }

        var updateDtoToVm = viewModel.Adapt<CandidateQuestionSubjectUpdateDto>();

        updateDtoToVm.Name = StringExtensions.TitleFormat(viewModel.Name);

        var updateResult = await _candidateQuestionSubjectService.UpdateAsync(updateDtoToVm);
        if (!updateResult.IsSuccess)
        {
            NotifyErrorLocalized(updateResult.Message);
        }
        else
        {
            NotifySuccessLocalized(updateResult.Message);
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Delete(Guid id)
    {
        var isQuestionUsed = await _candidateQuestionSubjectService.IsQuestionUsedInSubjectAsync(id);

        if (isQuestionUsed)
        {
            return await InactivateSubjectAndRelatedQuestionsWithAnswersAsync(id);
        }
        else
        {
            return await DeleteConfirmed(id);
        }
    }

    [HttpPost]
    public async Task<IActionResult> ActivateSubjectAndRelatedQuestionsWithAnswers(Guid id)
    {
        var result = await _candidateQuestionSubjectService.ActivateSubjectAndRelatedQuestionsWithAnswersAsync(id);
        if (!result.IsSuccess)
        {
            return Json(new { isSuccess = false, message = result.Message });
        }

        return Json(new { isSuccess = true });
    }

    [HttpPost]

    public async Task<IActionResult> InactivateSubjectAndRelatedQuestionsWithAnswersAsync(Guid id)
    {
        var result = await _candidateQuestionSubjectService.InactivateSubjectAndRelatedQuestionsWithAnswersAsync(id);
        if (!result.IsSuccess)
        {
            return Json(new { isSuccess = false, message = result.Message });
        }

        return Json(new { isSuccess = true });
    }


    // Helper Methods
    private async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        var deleteResult = await _candidateQuestionSubjectService.DeleteAsync(id);
        if (!deleteResult.IsSuccess)
        {
            NotifyErrorLocalized(deleteResult.Message);
        }
        else
        {
            NotifySuccessLocalized(deleteResult.Message);
        }

        return Json(deleteResult);
    }

    public async Task<IActionResult> CheckIfQuestionIsActive(Guid id)
    {
        // Konu ile ilişkili soruları al
        var result = await _candidateQuestionService.GetQuestionsBySubjectIdAsync(id);

        if (!result.IsSuccess)
        {
            return Json(new { hasActiveQuestions = false });
        }

        if (result.Data == null || !result.Data.Any())
        {
            return Json(new { hasActiveQuestions = false });
        }

        bool hasActiveQuestions = result.Data.Any(cq => cq.Status == Status.Active);

        // Sonucu döndür
        return Json(new { hasActiveQuestions });
    }
}

BAExamApp.MVC/Areas/CandidateAdmin/Views/CandidateQuestionSubject/Details.cshtml
@model CandidateAdminQuestionSubjectDetailVM

@{
    ViewData["Title"] = ViewLocalizer["Subject_Details"];
}

<div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
    <div class="card-header cursor-pointer">
        <div class="card-title m-0">
            <h5 class="text-center">@ViewLocalizer["Subject_Details"]</h5>
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn btn-secondary align-self-center ms-2" asp-controller="CandidateQuestionSubject" asp-action="Index">@SharedLocalizer["Back_List"]</a>
            <a class="btn btn-primary align-self-center ms-2" data-bs-toggle="modal" data-bs-target="#updateCandidateQuestionSubjectModal" data-subject-id="@Model.Id" data-subject-name="@Model.Name">
                @SharedLocalizer["Update"]
            </a>
            @if (Model.Status == Status.Active)
            {
                <a class="btn btn-danger align-self-center ms-2 deleteAction" data-id="@Model.Id">@SharedLocalizer["Delete"]</a>
            }
            else if (Model.Status == Status.Passive)
            {
                <a class="btn btn-success align-self-center ms-2 activateAction" data-id="@Model.Id">@SharedLocalizer["Activate"]</a>
            }
        </div>
    </div>
    <div class="card-body p-9">
        <div class="row mb-7">
            <label class="col-lg-2 fw-bold text-muted">@SharedLocalizer["Subject_Name"]:</label>
            <div class="col-lg-10 fv-row">
                <span class="fw-bold text-gray-800 fs-6">@Model.Name</span>
            </div>
        </div>
    </div>
</div>


<partial name="~/Areas/CandidateAdmin/Views/CandidateQuestionSubject/_UpdatePartialView.cshtml" model="new CandidateAdminQuestionSubjectUpdateVM()" />


@section Scripts
{
    <script src="~/js/CandidateQuestionSubjectUpdate.js"></script>
    <script src="~/lib/limonte-sweetalert2/sweetalert2.all.js"></script>
    <script>
        var deleteActionLocalizedTexts = {
            confirmTitle: '@SharedLocalizer["Confirm_Delete_Title"]',
            confirmText: '@SharedLocalizer["Confirm_Delete_Text"]',
            confirmButtonText: '@SharedLocalizer["Confirm_Button_Text"]',
            confirmPassiveButtonText: '@SharedLocalizer["Confirm_Passive_Button_Text"]',
            confirmActiveButtonText: '@SharedLocalizer["Confirm_Active_Button_Text"]',
            cancelButtonText: '@SharedLocalizer["Cancel_Button_Text"]',
            cancel: '@SharedLocalizer["Cancel"]',
            passiveTitle: '@SharedLocalizer["In_Use_SubjectTitle"]',
            passiveText: '@SharedLocalizer["In_Use_SubjectText"]',
            activeTitle: '@SharedLocalizer["Confirm_Active_Title"]',
            activeText: '@SharedLocalizer["Confirm_Active_Text"]',
            passiveActionButton: '@SharedLocalizer["Passive_Action_Button"]',
            threeUsedTitle: '@SharedLocalizer["Three_Used_Title"]',
            questionUsedSubjectTitle: '@SharedLocalizer["Question_Used_Subject_Title"]',
            deleteActionButton: '@SharedLocalizer["Confirm_Button_Text"]',
            deleteText: '@SharedLocalizer["Confirm_Delete_Text"]'
        };

        var updateActionLocalizedTexts = {
            unsavedChangesTitle: '@SharedLocalizer["Unsaved_Changes_Title"]',
            unsavedChangesText: '@SharedLocalizer["Unsaved_Changes_Text"]',
            confirmButtonText: '@SharedLocalizer["Yes_Leave"]',
            cancelButtonText: '@SharedLocalizer["No_Stay"]',
            formSubmittedText: '@SharedLocalizer["Form_Submitted_Text"]',
            okButtonText: '@SharedLocalizer["Ok_Button_Text"]'
        };
        
        $(".deleteAction, .activateAction").click(function () {
            const id = $(this).attr("data-id");
            const isActivateAction = $(this).hasClass("activateAction");
            var title, text, confirmBtnText, deleteBtnColor;

            if (isActivateAction) {
                title = deleteActionLocalizedTexts.activeTitle;
                text = deleteActionLocalizedTexts.activeText;
                confirmBtnText = deleteActionLocalizedTexts.confirmActiveButtonText;
                deleteBtnColor = '#28a745';
            } else {
                var isQuestionUsed = @Html.Raw(Json.Serialize(Model.IsQuestionUsed != null ? Model.IsQuestionUsed : false));

                if (isQuestionUsed) {
                    title = deleteActionLocalizedTexts.questionUsedSubjectTitle;
                    text = deleteActionLocalizedTexts.passiveText;
                    confirmBtnText = deleteActionLocalizedTexts.passiveActionButton;
                } 
                else {
                    title = deleteActionLocalizedTexts.confirmTitle;
                    text = deleteActionLocalizedTexts.deleteText;
                    confirmBtnText = deleteActionLocalizedTexts.deleteActionButton;
                }
                deleteBtnColor = (isQuestionUsed) ? '#28a745' : '#d33';
            }

            Swal.fire({
                title: title,
                text: text,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: deleteBtnColor,
                cancelButtonColor: '#3085d6',
                confirmButtonText: confirmBtnText,
                cancelButtonText: deleteActionLocalizedTexts.cancel
            }).then((result) => {
                if (result.isConfirmed) {
                    const url = isActivateAction ? "@Url.Action("ChangeStatus")" : "@Url.Action("Delete")";
                    $.ajax({
                        type: "GET",
                        url: url + "?id=" + id,
                        success: function (result) {
                            if (result.isSuccess) {
                                setTimeout(() => location.href = "@Url.Action("index")", 1000);
                            }
                        }
                    });
                }
            });
        });

    </script>

    /
    <script>
      
    </script>
}

BAExamApp.MVC/Areas/CandidateAdmin/Views/CandidateQuestionSubject/_CreatePartialView.cshtml
@model CandidateAdminQuestionSubjectCreateVM

@{
    ViewData["Title"] = ViewLocalizer["Create_Subject"];
}

<div class="modal fade" id="createCandidateQuestionSubjectModal" tabindex="-1" aria-labelledby="ProductAdd" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@SharedLocalizer["Create_New_Subject"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="CandidateQuestionSubject" asp-action="Create" class="form" id="create-questionSubject">
                <div class="modal-body">
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label col-form-label-lg"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" type="text" class="form-control form-control-lg form-control-solid" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                    <a class="btn btn-light align-self-center ms-2" asp-controller="CandidateQuestionSubject" asp-action="Index">@SharedLocalizer["Back_List"]</a>
                    <button class="btn btn-primary" type="submit">@SharedLocalizer["Save"]</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

BAExamApp.MVC/Areas/CandidateAdmin/Views/CandidateQuestionSubject/_UpdatePartialView.cshtml
@model CandidateAdminQuestionSubjectUpdateVM

@{
    ViewData["Title"] = ViewLocalizer["Update"];
}

<div class="modal fade" id="updateCandidateQuestionSubjectModal" tabindex="-1" aria-labelledby="updateCandidateQuestionSubjectModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form asp-controller="CandidateQuestionSubject" asp-action="Update" method="post" id="updateCandidateQuestionSubjectForm">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateSubjectModalLabel">@SharedLocalizer["Subject_Update"]</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3">
                        <label asp-for="Name" class="form-label">@SharedLocalizer["Subject_Name"]</label>
                        <input asp-for="Name" type="text" class="form-control" required>
                    </div>
                    <input asp-for="Id" type="hidden" />
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary align-self-center ms-2" asp-controller="CandidateQuestionSubject" asp-action="Index">@SharedLocalizer["Back_List"]</a>
                    <button type="submit" class="btn btn-success">@SharedLocalizer["Save"]</button>
                </div>
            </form>
        </div>
    </div>
</div>