BAExamApp.MVC/Areas/CandidateAdmin/Controllers/CandidateQuestionController.cs
using BAExamApp.DataAccess.Interfaces.Repositories.Candidate;
using BAExamApp.Dtos.Candidate.CandidateQuestionAnswers;
using BAExamApp.MVC.Areas.CandidateAdmin.Models.CandidateQuestionAnswerVMs;
using BAExamApp.MVC.Areas.CandidateAdmin.Models.CandidateQuestionVMs;
using BAExamApp.MVC.Extensions;
using Microsoft.Extensions.Localization;
using System.ComponentModel.DataAnnotations;
using System.Reflection;


namespace BAExamApp.MVC.Areas.CandidateAdmin.Controllers;
public class CandidateQuestionController : CandidateAdminBaseController
{
    private readonly ICandidateQuestionService _candidateQuestionService;
    private readonly ICandidateAnswerService _candidateAnswerService;
    private readonly ICandidateCandidateAnswerRepository _candidateCandidateAnswerRepository;
    private readonly ICandidateQuestionSubjectService _candidateQuestionSubjectService;
    private readonly IStringLocalizer<SharedModelResource> _stringLocalizer;

    public CandidateQuestionController(ICandidateQuestionService candidateQuestionService, ICandidateAnswerService candidateAnswerService, ICandidateCandidateAnswerRepository candidateCandidateAnswerRepository,ICandidateQuestionSubjectService candidateQuestionSubjectService, IStringLocalizer<SharedModelResource> stringLocalizer)
    {
        _candidateQuestionService = candidateQuestionService;
        _candidateAnswerService = candidateAnswerService;
        _candidateCandidateAnswerRepository = candidateCandidateAnswerRepository;
        _candidateQuestionSubjectService = candidateQuestionSubjectService;
        _stringLocalizer = stringLocalizer;
    }

    public async Task<IActionResult> Index(bool showAllQuestions = false, bool showPassiveQuestions = false)
    {
        ViewBag.ShowAllQuestions = showAllQuestions;

        var vm = new CandidateQuestionIndexVM()
        {
            CandidateQuestionTypeList = GetCandidateQuestionTypeList(),
            CandidateQuestionSubjectList = await GetCandidateSubjectListAsync()
        };

        return View(vm);
    }

    [HttpPost]
    public async Task<IActionResult> Index(CandidateQuestionIndexVM candidateQuestionIndexVM)
    {
        var result = await _candidateQuestionService.GetQuestionBySearchValues(candidateQuestionIndexVM.Content, candidateQuestionIndexVM.CandidateQuestionTypeIndex, candidateQuestionIndexVM.CandidateQuestionSubjectIndex);



        var subjects = await _candidateQuestionSubjectService.GetAllAsync();
        ViewBag.CandidateQuestionSubjects = subjects.Data;




        if (result.IsSuccess)
        {
            if (candidateQuestionIndexVM.ShowPassiveQuestions)
            {
                candidateQuestionIndexVM.QuestionList = result.Data.Adapt<List<CandidateQuestionListVM>>();
            }
            else
            {
                candidateQuestionIndexVM.QuestionList = result.Data.Where(x => x.Status == Core.Enums.Status.Active).Adapt<List<CandidateQuestionListVM>>();
            }
            NotifySuccessLocalized(result.Message);
        }
        else
        {
            NotifyErrorLocalized(result.Message);
        }
        candidateQuestionIndexVM.CandidateQuestionTypeList = GetCandidateQuestionTypeList();
        candidateQuestionIndexVM.CandidateQuestionSubjectList = await GetCandidateSubjectListAsync();
        return View(candidateQuestionIndexVM);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var subjects=await _candidateQuestionSubjectService.GetAllAsync();
        var subjectList = subjects.Data.Where(x => x.Status != Core.Enums.Status.Passive).ToList();

        ViewBag.CandidateQuestionSubjects = subjectList;
        ViewBag.CandidateQuestionType = GetCandidateQuestionTypeList();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CandidateQuestionCreateVM candidateQuestionCreateVM, IFormCollection collection)
    {
        List<CandidateAnswerCreateVM> questionAnswersList = JsonSerializer.Deserialize<List<CandidateAnswerCreateVM>>(collection["questionAnswerChoices"]);

        candidateQuestionCreateVM.QuestionAnswers = questionAnswersList;

        var question = candidateQuestionCreateVM.Adapt<CandidateQuestionCreateDto>();
        if (candidateQuestionCreateVM.NewImage != null)
        {
            question.Image = await candidateQuestionCreateVM.NewImage.FileToByteArrayAsync();
        }

        var addResult = await _candidateQuestionService.AddAsync(question);
        if (!addResult.IsSuccess)
        {
            NotifyErrorLocalized(addResult.Message);

            ViewBag.CandidateQuestionType = GetCandidateQuestionTypeList();
            ViewBag.QuestionAnswersList = JsonSerializer.Serialize(questionAnswersList);

            return View(candidateQuestionCreateVM);
        }

        NotifySuccessLocalized(addResult.Message);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Details(Guid id)
    {
        var result = await _candidateQuestionService.GetDetailsByIdAsync(id);
        if (!result.IsSuccess)
        {
            NotifyErrorLocalized(result.Message);
            return NotFound();
        }
        else
        {
            NotifySuccessLocalized(result.Message);
        }

        var candidateQuestionDetailsVM = result.Data.Adapt<CandidateQuestionDetailsVM>();

        var localizedType = _stringLocalizer[Enum.GetName(typeof(CandidateQuestionType), candidateQuestionDetailsVM.CandidateQuestionType)];
        candidateQuestionDetailsVM.CandidateQuestionTypeString = localizedType;
        if (candidateQuestionDetailsVM.CandidateQuestionSubject!=null)
        candidateQuestionDetailsVM.CandidateQuestionSubjectString = candidateQuestionDetailsVM.CandidateQuestionSubject.Name;
        return Json(candidateQuestionDetailsVM);
    }

    [HttpGet]
    public async Task<IActionResult> Update(Guid id)
    {
        var questionResult = await _candidateQuestionService.GetByIdWithFilteredAnswersAsync(id);

        if (!questionResult.IsSuccess)
            return NotFound();

     

        CandidateQuestionUpdateVM candidateQuestionUpdateVM = questionResult.Data.Adapt<CandidateQuestionUpdateVM>();
        candidateQuestionUpdateVM.CandidateQuestionTypeList = GetCandidateQuestionTypeList();
        candidateQuestionUpdateVM.QuestionAnswersList = JsonSerializer.Serialize(candidateQuestionUpdateVM.QuestionAnswers);
        ViewBag.QuestionAnswersList = candidateQuestionUpdateVM.QuestionAnswersList;
        candidateQuestionUpdateVM.Image = questionResult.Data.Image;
        return Json(candidateQuestionUpdateVM);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(CandidateQuestionUpdateVM candidateQuestionUpdateVM, IFormCollection collection)
    {
        var updateQuestionResult = await _candidateQuestionService.GetByIdAsync(candidateQuestionUpdateVM.Id);
        if (!updateQuestionResult.IsSuccess)
        {
            NotifyErrorLocalized(updateQuestionResult.Message);
            return RedirectToAction(nameof(Index));
        }

        List<CandidateAnswerUpdateVM> questionAnswersList = JsonSerializer.Deserialize<List<CandidateAnswerUpdateVM>>(collection["questionAnswerChoices"]);

        // Resim kaldırma durumu kontrol ediliyor
        bool removeImage = collection["removeImageHidden"].ToString().ToLower() == "true";
        if (removeImage)
        {
            candidateQuestionUpdateVM.Image = null;
        }
        else if (candidateQuestionUpdateVM.NewImage != null)
        {
            candidateQuestionUpdateVM.Image = await candidateQuestionUpdateVM.NewImage.FileToByteArrayAsync();
        }
        else
        {
            candidateQuestionUpdateVM.Image = updateQuestionResult.Data.Image;
        }


        if (questionAnswersList.Count > 0)
        {
            var existingAnswers = updateQuestionResult.Data.QuestionAnswers;
            var updatedAnswers = questionAnswersList.Select(qa => qa.Id).ToList();

            var answersToUpdate = questionAnswersList.Where(qa => existingAnswers.Any(ea => ea.Id == qa.Id)).ToList();
            var answersToAdd = questionAnswersList.Where(qa => !existingAnswers.Any(ea => ea.Id == qa.Id)).ToList();
            var answersToDelete = existingAnswers
                .Where(ea => !updatedAnswers.Contains(ea.Id) && ea.Status != (Core.Enums.Status)4)
                .ToList();

            // Cevapları güncelle
            foreach (var answerToUpdate in answersToUpdate)
            {
                var updateResult = await _candidateAnswerService.UpdateAsync(answerToUpdate.Adapt<CandidateAnswerUpdateDto>());
                if (!updateResult.IsSuccess)
                {
                    NotifyErrorLocalized(updateResult.Message);
                    return RedirectToAction(nameof(Index));
                }
            }

            // Yeni cevapları ekle
            foreach (var answerToAdd in answersToAdd)
            {
                answerToAdd.QuestionId = candidateQuestionUpdateVM.Id;
                var addResult = await _candidateAnswerService.AddAsync(answerToAdd.Adapt<CandidateAnswerCreateDto>());
                if (!addResult.IsSuccess)
                {
                    NotifyErrorLocalized(addResult.Message);
                    return RedirectToAction(nameof(Index));
                }
            }

            // Silinecek cevapları sil
            foreach (var answerToDelete in answersToDelete)
            {
                var deleteResult = await _candidateAnswerService.DeleteAsync(answerToDelete.Id);
                if (!deleteResult.IsSuccess)
                {
                    NotifyErrorLocalized(deleteResult.Message);
                    return RedirectToAction(nameof(Index));
                }
            }
        }

        // Soruyu güncelle
        var candidateQuestionUpdateDto = candidateQuestionUpdateVM.Adapt<CandidateQuestionUpdateDto>();

BAExamApp.MVC/Areas/CandidateAdmin/Views/CandidateQuestion/Create.cshtml
@using BAExamApp.Dtos.Candidate.CandidateQuestionSubject
@{
    ViewData["Title"] = "Create";
}
@model CandidateQuestionCreateVM


<head>
    <link rel="stylesheet" href="~/css/candidateQuestion/candidateQuestionCreate.css" />
</head>

<div class="card">
    <!--begin::Card header-->
    <div class="ps-9 pt-6">
        <h1 class="text-dark fw-bolder fs-1">@ViewLocalizer["Add_Candidate_Question_Page"]</h1>
    </div>
    <!--end::Card header-->
    <!--begin::Card body-->
    <div class="card-body ">
        <!--begin::Form-->
        <form id="candidateQuestionForm" asp-controller="CandidateQuestion" asp-action="Create" class="form" enctype="multipart/form-data">
            <div class="row mb-3">
                <input class="form-control" name="questionAnswersListFromReload" id="questionAnswersListFromReload" value="@ViewBag.QuestionAnswersList" hidden />
                <div class="col-sm-12">
                    <div class="fv-row form-floating mb-7">
                        <select asp-for="CandidateQuestionType" class="form-select form-select-sm form-select-solid" onchange="onQuestionTypeChange()" id="QuestionType">
                            @foreach (SelectListItem questionType in ViewBag.CandidateQuestionType)
                            {
                                <!option value="@questionType.Value" title="@GetDescriptionForQuestionType(questionType.Value)" @(questionType.Value == "1" ? "selected" : null)>
                                    @SharedLocalizer[$"{questionType.Text}"]
                                </!option>
                            }
                        </select>
                        <label asp-for="CandidateQuestionType" class="fw-bold fs-6 mb-2">@SharedLocalizer["Question_Type"]</label>
                    </div>
                </div>

                <div class="col-sm-12">
                    <div class="fv-row form-floating mb-7">
                        <select asp-for="CandidateQuestionSubjectId" class="form-select form-select-sm form-select-solid" id="QuestionType">
                            @foreach (var subject in ViewBag.CandidateQuestionSubjects)
                            {
                                <!option value="@subject.Id">
                                    @subject.Name
                                </!option>
                            }
                        </select>
                        <label asp-for="CandidateQuestionType" class="fw-bold fs-6 mb-2">@SharedLocalizer["Subject"]</label>
                    </div>
                </div>

                <input class="form-control" name="questionAnswerChoices" id="questionAnswerChoices" hidden />
                <div class="col-sm-12">
                    <div class="fv-row form-floating mb-7">
                        <textarea asp-for="Content" rows="4" class="form-control form-control-sm form-control-solid" 
                        oninput="auto_grow(this)"
                        style="resize: none; overflow: hidden; font-size: 1em;"></textarea>
                        <label asp-for="Content" class="fw-bold fs-6 mb-2">@SharedLocalizer["Question_Content"]</label>
                    </div>
                </div>
                <div class="col-sm-6">
                        <label asp-for="NewImage" class="col-sm-12 col-form-label col-form-label-lg">@SharedLocalizer["Question_Image"] </label>
                        <input asp-for="NewImage" type="file" class="form-control form-control-lg form-control-solid" id="fileInput" accept=".png,.jpeg,.jpg" hidden />
                    <div class="fv-row form-floating mb-7 w-100 h-100">
                        <div class="image-input image-input-outline fv-row w-100 h-100"
                             data-kt-image-input="true"
                             style="position: relative;">
                            <div class="image-container w-100 h-100">
                                <span type="button" id="uploadImageButton" class="btn btn-icon btn-circle btn-active-color-primary w-12px h-12px bg-body"
                                      data-bs-toggle="tooltip" title="@SharedLocalizer["Upload_Question_Picture"]">
                                    <i class="bi bi-pencil-fill fs-7"></i>
                                </span>
                                <img id="previewImage"
                                     alt="Preview" />
                                <div id="imagePlaceholder">
                                    <span>
                                        <i class="bi bi-image"></i>
                                    </span>
                                    <p>@SharedLocalizer["Image_Upload_Placeholder_Info"]</p>
                                </div>
                                <span type="button" id="removeImageButton" class="btn btn-icon btn-circle btn-active-color-primary w-12px h-12px bg-body"
                                      data-bs-toggle="tooltip" title="@SharedLocalizer["Remove_Question_Picture"]">
                                    <i class="bi bi-x fs-2"></i>
                                </span>
                            </div>
                        </div>
                        <input type="hidden" id="removeImageHidden" name="removeImageHidden" value="false" />
                    </div>
                </div>

                <div class="col-sm-6 gap-3 " id="questionAnswersDiv" hidden>
                    <label asp-for="QuestionAnswers" class="col-sm-12 col-form-label col-form-label-lg">@SharedLocalizer["Question_Answers"]</label>
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex mt-8  justify-content-md-end m-3">

                <a asp-action="Index" asp-route-showAllQuestions="true" class="btn p-5 mx-2 btn-primary">@SharedLocalizer["Back_List"]</a>
                <button class="btn btn-success" type="button" onclick="validateAndSubmitForm()">@SharedLocalizer["Save"]</button>
            </div>
        </form>
        <!--end::Form-->
    </div>



    <!--end::Card body-->
</div>





@section Scripts {
    <script src="~/js/candidateQuestionCreate.js"></script>
    <script>
        var localizer = {
            choose: '@SharedLocalizer["Choose"]',
            answers: '@SharedLocalizer["Answers"]',
            newoption: '@SharedLocalizer["New_Option"]',
            addnewoption: '@SharedLocalizer["Add_New_Options"]',
            text: '@SharedLocalizer["Text"]',
            image: '@SharedLocalizer["Image"]',
            newAnswer: '@SharedLocalizer["New_Answer"]'
        };

        var validationMessages = {
            pleaseProvideQuestionContent: '@SharedLocalizer["Please_Provide_Question_Content"]',
            imageFileSizeErrorTitle: '@SharedLocalizer["Image_File_Size_Error_Title"]',
            imageFileSizeErrorText: '@SharedLocalizer["Image_File_Size_Error_Text"]',
            missingDataErrorTitle: '@SharedLocalizer["Missing_Data_Error_Title"]',
            addAnswerErrorText: '@SharedLocalizer["Add_Answer_Error_Text"]',
            minAnswersErrorText: '@SharedLocalizer["Min_Answers_Error_Text"]',
            selectCorrectAnswerErrorText: '@SharedLocalizer["Select_Correct_Answer_Error_Text"]'
        };

        // Bu fonksiyon, soru tipine bağlı olarak açıklama ekler
        function updateDescription() {
            var selectedQuestionType = document.getElementById('QuestionType').value;


            var description = getQuestionTypeDescription(selectedQuestionType);


            var descriptionTextArea = document.getElementById('questionTypeDescription');
            descriptionTextArea.value = description;


            var container = document.getElementById('questionTypeDescriptionContainer');
            if (description.trim() !== '') {
                container.style.display = 'block';
            } else {
                container.style.display = 'none';
            }
        }

        @functions {
        public static string GetDescriptionForQuestionType(string questionTypeId)
        {
            switch (questionTypeId)
            {
                case "1":
                    return "İlgili sorunun bir doğru cevabı işaretlenebilir.";
                case "2":
                    return "İlgili sorunun bir doğru cevabı metin şeklinde kod içerir.";
                case "3":
                    return "İlgili sorunun doğru cevabı metin şeklindedir.";
                default:
                    return "Soru tipi hakkında bilgi bulunamadı.";

            }
        }
    }

        function showTooltip(element) {
            var tooltipText = element.getAttribute('data-title');
            if (tooltipText) {
                alert(tooltipText);
            }
        }

    document.addEventListener('DOMContentLoaded', function () {
        updateDescription();
    });

    document.getElementById('QuestionType').addEventListener('change', function () {
        updateDescription();
    });

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        onQuestionTypeChange()
    });

    function auto_grow(element) {
        element.style.height = "auto";
        element.style.height = (element.scrollHeight) + "px";
        element.style.overflow = "hidden";
    }
</script>
<script>
    document.getElementById("removeImageButton").addEventListener("click", function () {
       https://localhost:44326/images/bilgeadam-logo.jpg var removeImageHidden = document.getElementById("removeImageHidden");
        var previewImage = document.getElementById("previewImage");
        var removeImageButton = document.getElementById("removeImageButton");
        var imagePlaceholder = document.getElementById("imagePlaceholder");

            previewImage.src = "";
            previewImage.style.display = "none"; 
            removeImageButton.style.display = "none"
            imagePlaceholder.style.display = "flex"
            removeImageHidden.value = "true";
    });

    // Resim ekleme inputunu dinleyen bir işlev
    document.getElementById("fileInput").addEventListener("change", function (event) {
        var file = event.target.files[0];
        var imageType = /image.*/;

        if (file.type.match(imageType)) {
            var reader = new FileReader();

            // Dosya okunduğunda ön izlemeyi güncelle
            reader.onload = function (e) {
                var previewImage = document.getElementById("previewImage");
                var removeImageButton = document.getElementById("removeImageButton");
                var imagePlaceholder = document.getElementById("imagePlaceholder");

                previewImage.src = e.target.result;
                previewImage.style.display = "block"; 
                removeImageButton.style.display = "block";
                imagePlaceholder.style.display = "none";
                document.getElementById("removeImageHidden").value = "false";
            }

            // Dosyayı oku
            reader.readAsDataURL(file);
        }
    });

    document.getElementById("uploadImageButton").addEventListener("click", function () {
        document.getElementById("fileInput").click();

    });
</script>
}

BAExamApp.MVC/Areas/CandidateAdmin/Views/CandidateQuestion/Details.cshtml
@model CandidateQuestionDetailsVM

<div class="card py-16 ">
    <div class="d-flex justify-content-between ps-9 pt-6">
        <!--begin::Card title-->
        <div>
            <h3 class="fw-bolder m-0">@SharedLocalizer["Question_Detail"]</h3>
        </div>
        <!--end::Card title-->
        <!--begin::Action-->
        <div class="d-flex align-items-center">
            <a asp-controller="CandidateQuestion" asp-action="CopyQuestion" asp-route-id="@Model.Id" class="btn px-2 mx-2 btn-success">@SharedLocalizer["Copy_Question"]</a>
        </div>
        <!--end::Action-->
    </div>
    <div class="card-body row fs-6 py-15 px-10 py-lg-15 px-lg-15">
        <div class="col-lg-6 mb-3">
            <div class="row mb-7">
                <label class="w-150px fw-bold text-muted">@Html.DisplayNameFor(model => model.CreatedDate) :</label>
                <div class="col-xl-8 col-12">
                    <span class="fw-bolder fs-6 text-gray-800">@Model.CreatedDate.ToShortDateString()</span>
                </div>
            </div>

            <div class="row mb-7">
                <label class="w-150px fw-bold text-muted">
                    @Html.DisplayNameFor(model => model.CandidateQuestionType) :
                </label>
                <div class="col-xl-8 col-12">
                    <span class="fw-bolder fs-6 text-gray-800">
                        @SharedLocalizer[Enum.GetName(typeof(CandidateQuestionType), Model.CandidateQuestionType)]
                    </span>
                </div>
            </div>
            <div class="row mb-7">
                <label class="w-150px fw-bold text-muted">
                    @Html.DisplayNameFor(model => model.Content) :
                </label>
                <div class="col-xl-8 col-12">
                    <span class="fw-bolder fs-6 text-gray-800">
                        @Html.DisplayFor(model => model.Content)
                    </span>
                </div>
            </div>
        </div>
        @if (Model.Image != null)
        {
            <div class="row col-lg-4 mb-3">
                <label class=" fw-bold text-muted mb-3">
                    @Html.DisplayNameFor(model => model.Image)
                </label>
                <div class="image-input image-input-outline fv-row"
                     data-kt-image-input="true">
                    <div class="col-lg-12"
                         style="display: flex; justify-content: flex-start">
                        <img id="defaultImage"
                             class="col-lg-12 img-fluid"
                             src="data:image/jpeg;base64,@Model.Image"
                             alt="Profile" />
                    </div>
                </div>
            </div>
        }
        <hr />
        <div class="row mb-7">
            <label class="w-150px fw-bold text-muted">
                @Html.DisplayNameFor(model => model.QuestionAnswers) :
            </label>
            <div class="col-xl-10 col-12">
                @foreach (var item in Model.QuestionAnswers)
                {
                    @if (item.IsRightAnswer)
                    {
                        <p class="fw-bolder fs-6 text-gray-800">
                            @SharedLocalizer[item.Answer]
                            <span class="badge badge-success">@SharedLocalizer["True"]</span>
                        </p>
                    }
                    else
                    {
                        <p class="fw-bolder fs-6 text-gray-800">
                            @SharedLocalizer[item.Answer]
                        </p>

                    }
                }
            </div>
        </div>
    </div>
</div>

BAExamApp.MVC/Areas/CandidateAdmin/Views/CandidateQuestion/_CandidateQuestionDetailsPartialView.cshtml
@model CandidateQuestionDetailsVM

<head>
    <link rel="stylesheet" href="~/css/candidateQuestion/candidateQuestionDetails.css" />
</head>

<div class="modal fade" id="kt_modal_details_question" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered mw-1000px">
        <div class="modal-content">
            <div class="modal-header" id="kt_modal_details_question_header">
                <h3>@SharedLocalizer["Question_Detail"]</h3>
                <div class="btn btn-icon btn-sm btn-active-icon-primary" data-kt-question-details-modal-action="close">
                    <span class="svg-icon svg-icon-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor" />
                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor" />
                        </svg>
                    </span>
                </div>
            </div>
            <div class="modal-body scroll-y mx-5 mx-xl-15 my-7">
                <form asp-area="CandidateAdmin" asp-controller="CandidateQuestion" asp-action="Details" id="kt_modal_details_question_form" class="form" enctype="multipart/form-data">
                    <div class="d-flex flex-column scroll-y me-n7 pe-7" id="kt_modal_details_question_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_details_question_header" data-kt-scroll-wrappers="#kt_modal_details_question_scroll" data-kt-scroll-offset="300px">
                        <div class="row mb-3 fv-row">
                            <input asp-for="Id" name="id" class="form-control" id="id" hidden />

                            <div id="questionTypeContainer"></div>

                            @* Oluşturulma Tarihi *@
                            <div class="col-sm-12">
                                <div class="fv-row form-floating mb-7">
                                    <p class="form-control form-control-sm form-control-solid" id="CreatedDateDisplay"></p>
                                  
                                    <label class="fw-bold fs-6 mb-2">@SharedLocalizer["Created_Date"]  </label>
                             
                                </div>
                            </div>



                            @* Soru Tipi *@
                            <div class="col-sm-12">
                                <div class="fv-row form-floating mb-7">
                                    <p class="form-control form-control-sm form-control-solid" id="CandidateQuestionTypeDisplay"></p>
                                    <label class="fw-bold fs-6 mb-2">@SharedLocalizer["Question_Type"]</label>
                                </div>
                            </div>

                            @* Soru Konusu *@
                            <div class="col-sm-12">
                                <div class="fv-row form-floating mb-7">
                                    <p class="form-control form-control-sm form-control-solid" id="CandidateSubjectDisplay"></p>

                                    <label class="fw-bold fs-6 mb-2">@SharedLocalizer["Question_Subject"]  </label>

                                </div>
                            </div>


                            @* Soru İçeriği *@
                            <div class="col-sm-12">
                                <div class="fv-row form-floating mb-7">
                                    <p class="form-control form-control-sm form-control-solid" id="ContentDisplay"></p>
                                    <label class="col-sm-12 col-form-label col-form-label-lg">@SharedLocalizer["Question_Content"]</label>
                                </div>
                            </div>


                            @* Soru Resmi ve Yanıtlar *@
                            <div class="col-sm-6 flex-container" id="questionAndAnswersContainer">
                                <div class="image-container-details" id="arrangeReason">
                                    <label class="col-sm-6 col-form-label col-form-label-md" id="questionImageLabel">@SharedLocalizer["Question_Image"]</label>
                                    <div class="fv-row form-floating mb-7">
                                        <div class="image-input image-input-outline fv-row" data-kt-image-input="true" style="position: relative;">
                                            <div style="display: flex; justify-content: flex-start">
                                                <img id="defaultImage" style="display: none;" alt="Profile" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                @* Soru Yanıtları *@
                                <div id="questionAnswersDiv">
                                    <label id="questionAnswersLabel" class="col-sm-6 col-form-label col-form-label-lg" style="display: none;">
                                        @SharedLocalizer["Question_Answers"]
                                    </label>
                                    <label id="questionAnswerLabel" class="col-sm-6 col-form-label col-form-label-lg" style="display: none;">
                                        @SharedLocalizer["Question_Answer"]
                                    </label>
                                    <div id="questionAnswersDisplay"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="text-center pt-15">
                        <button type="reset" class="btn btn-light me-3" data-kt-question-details-modal-action="cancel">@SharedLocalizer["Back_List"]</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>